# Generated by Django 3.0.4 on 2020-11-27 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(default='event_title', max_length=40, verbose_name='Titulo de la solicitud')),
                ('status', models.CharField(default='Necesita revision', max_length=20, verbose_name='Estado de la solicitud')),
                ('specification', models.CharField(default='especification', max_length=100, verbose_name='Especificación')),
                ('observation', models.CharField(default='observation', max_length=300, verbose_name='Oberservaciones')),
                ('time_create', models.DateTimeField(auto_now=True)),
                ('response', models.CharField(default='response', max_length=400, verbose_name='Respuesta')),
                ('petitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.Client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(default='event_title', max_length=40, verbose_name='Titulo de la solicitud')),
                ('status', models.CharField(default='Necesita revision', max_length=20, verbose_name='Estado de la solicitud')),
                ('specification', models.CharField(default='especification', max_length=100, verbose_name='Especificación')),
                ('observation', models.CharField(default='observation', max_length=300, verbose_name='Oberservaciones')),
                ('time_create', models.DateTimeField(auto_now=True)),
                ('event_type', models.IntegerField(choices=[(1, 'Evento en general'), (2, 'Torneo deportivo Individual'), (3, 'Torneo deportivo por equipos'), (4, 'otro tipo')], default=3, verbose_name='Tipo de evento')),
                ('event_place', models.IntegerField(choices=[(1, 'Multicancha'), (2, 'Pista Atlética'), (3, 'Psicina'), (4, 'Cancha Sintetica'), (5, 'Gimnasio completo'), (6, 'Lugar Externo')], default='6', verbose_name='Lugar del evento')),
                ('event_date', models.DateField(default='2020-11-09', verbose_name='Fecha del evento')),
                ('init_hour', models.TimeField(default='08:00 a.m', verbose_name='Hora inicial')),
                ('finish_hour', models.TimeField(default='09:00 a.m', verbose_name='Hora Final')),
                ('petitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.Client')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
