# Generated by Django 3.0.4 on 2020-11-02 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
        ('Solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='third_event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(default='event_title', max_length=40)),
                ('event_type', models.CharField(default='event_type', max_length=15)),
                ('event_place', models.CharField(default='event_place', max_length=30)),
                ('event_date', models.DateField()),
                ('init_hour', models.TimeField()),
                ('finish_hour', models.TimeField()),
                ('specification', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('observation', models.CharField(max_length=500)),
                ('time_create', models.DateTimeField()),
                ('petitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.Client')),
            ],
        ),
    ]
