# Generated by Django 3.0.4 on 2020-11-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitudes', '0002_third_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='third_event',
            name='status',
            field=models.CharField(default='status', max_length=20),
        ),
    ]
