# Generated by Django 3.0.4 on 2020-09-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitudes', '0002_event_request_petitioner'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_request',
            name='observation',
            field=models.CharField(default='s', max_length=500),
            preserve_default=False,
        ),
    ]
