# Generated by Django 3.0.4 on 2021-01-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitudes', '0003_auto_20210116_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notify',
            name='object_id',
            field=models.PositiveIntegerField(default=13),
        ),
    ]
