# Generated by Django 3.0.4 on 2020-11-02 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
        ('Solicitudes', '0003_auto_20201102_1313'),
    ]

    operations = [
        migrations.DeleteModel(
            name='prueba',
        ),
        migrations.RemoveField(
            model_name='event_request',
            name='text',
        ),
        migrations.AddField(
            model_name='event_request',
            name='specification',
            field=models.CharField(default='especification', max_length=100),
        ),
        migrations.AlterField(
            model_name='event_request',
            name='event_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='event_request',
            name='event_place',
            field=models.CharField(default='event_place', max_length=30),
        ),
        migrations.AlterField(
            model_name='event_request',
            name='event_title',
            field=models.CharField(default='event_title', max_length=40),
        ),
        migrations.AlterField(
            model_name='event_request',
            name='event_type',
            field=models.CharField(default='event_type', max_length=15),
        ),
        migrations.AlterField(
            model_name='event_request',
            name='finish_hour',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='event_request',
            name='init_hour',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='event_request',
            name='observation',
            field=models.CharField(default='observation', max_length=500),
        ),
        migrations.AlterField(
            model_name='event_request',
            name='petitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.Client'),
        ),
        migrations.AlterField(
            model_name='event_request',
            name='status',
            field=models.CharField(default='status', max_length=20),
        ),
        migrations.AlterField(
            model_name='event_request',
            name='time_create',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
