# Generated by Django 3.0.4 on 2020-11-02 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitudes', '0004_auto_20201102_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='third_event',
            name='petitioner',
        ),
        migrations.DeleteModel(
            name='request_event',
        ),
        migrations.DeleteModel(
            name='third_event',
        ),
    ]
