# Generated by Django 3.0.4 on 2020-09-28 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitudes', '0004_auto_20200905_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='event_request',
            name='event_date',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='event_request',
            name='event_place',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='event_request',
            name='event_title',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='event_request',
            name='event_type',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='event_request',
            name='finish_hour',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='event_request',
            name='init_hour',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='event_request',
            name='observation',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.AlterField(
            model_name='event_request',
            name='status',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='event_request',
            name='text',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
