# Generated by Django 3.0.4 on 2020-11-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitudes', '0005_auto_20201102_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_request',
            name='observation',
            field=models.CharField(default='observation', max_length=300),
        ),
    ]
