# Generated by Django 3.0.4 on 2020-09-28 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
        ('Solicitudes', '0005_auto_20200927_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_request',
            name='petitioner',
            field=models.ForeignKey(blank=True, default='None', null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.Client'),
        ),
    ]
