# Generated by Django 3.0.4 on 2020-11-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitudes', '0007_auto_20201109_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_request',
            name='finish_hour',
            field=models.TimeField(default='09:00 a.m'),
        ),
        migrations.AlterField(
            model_name='event_request',
            name='init_hour',
            field=models.TimeField(default='08:00 a.m'),
        ),
    ]
