# Generated by Django 3.0.4 on 2020-11-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitudes', '0009_info_request_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_request',
            name='event_date',
            field=models.DateField(default='2020-11-09'),
        ),
    ]
