# Generated by Django 3.0.4 on 2020-11-27 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Solicitudes', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ind_event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(default=1)),
                ('event_title', models.CharField(default='event_title', max_length=40)),
                ('event_type', models.CharField(default='event_type', max_length=15)),
                ('event_place', models.CharField(default='event_place', max_length=30)),
                ('specification', models.CharField(default='especification', max_length=100)),
                ('init_hour', models.TimeField(default='08:00 a.m')),
                ('finish_hour', models.TimeField(default='09:00 a.m')),
                ('e_request', models.CharField(default='NoRequest', max_length=100)),
                ('event_date', models.DateField(default='2020-11-09')),
                ('content_type', models.ForeignKey(default=1, limit_choices_to=models.Q(models.Q(('app_label', 'Eventos'), ('model', 'single_championship')), models.Q(('app_label', 'Eventos'), ('model', 'team_championship')), models.Q(('app_label', 'Eventos'), ('model', 'other_event')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.Admin')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dep_event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(default=1)),
                ('content_type', models.ForeignKey(default=1, limit_choices_to=models.Q(models.Q(('app_label', 'Eventos'), ('model', 'single_championship')), models.Q(('app_label', 'Eventos'), ('model', 'team_championship')), models.Q(('app_label', 'Eventos'), ('model', 'other_event')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.Admin')),
                ('e_request', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Solicitudes.Event_request')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
