# Generated by Django 3.0.4 on 2020-10-30 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Logistica', '0001_initial'),
    ]

    operations = [
    ]
