# Generated by Django 3.0.4 on 2021-01-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logistica', '0002_auto_20201130_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_title',
            field=models.CharField(default='titulo', max_length=60),
        ),
    ]
