# Generated by Django 3.1.7 on 2021-04-09 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Logistica', '0003_auto_20210116_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ind_event',
            name='e_request',
        ),
    ]
