# Generated by Django 3.0.4 on 2020-11-09 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitudes', '0007_auto_20201109_1348'),
        ('Logistica', '0003_event_calendar'),
    ]

    operations = [
        migrations.CreateModel(
            name='other_event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('e_request', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Solicitudes.Event_Request')),
            ],
        ),
    ]
