# Generated by Django 3.0.4 on 2020-11-09 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Logistica', '0004_other_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='other_event',
            name='date',
        ),
    ]
