# Generated by Django 3.0.4 on 2020-11-21 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0008_delete_normal_person'),
        ('Solicitudes', '0010_auto_20201110_1440'),
        ('Logistica', '0005_remove_other_event_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ind_event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='None', max_length=100)),
                ('event', models.CharField(default='None', max_length=100)),
                ('e_request', models.CharField(default='NoRequest', max_length=100)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.Admin')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dep_event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='None', max_length=100)),
                ('event', models.CharField(default='None', max_length=100)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.Admin')),
                ('e_request', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Solicitudes.Event_Request')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
