# Generated by Django 3.0.4 on 2020-11-21 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logistica', '0006_dep_event_ind_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dep_event',
            name='date',
        ),
        migrations.RemoveField(
            model_name='ind_event',
            name='date',
        ),
        migrations.AddField(
            model_name='ind_event',
            name='event_date',
            field=models.DateField(default='2020-11-09'),
        ),
    ]
