# Generated by Django 3.0.4 on 2020-11-27 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='athlete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Franco', max_length=40, verbose_name='Nombre')),
                ('last_name', models.CharField(default='Vega', max_length=40, verbose_name='Apellido')),
                ('age', models.CharField(default='24', max_length=40)),
                ('email', models.CharField(default='hola@hola.com', max_length=40)),
                ('status', models.CharField(default='noActive', max_length=40)),
                ('results', models.CharField(default='noWin', max_length=40)),
                ('event', models.IntegerField(default=0)),
                ('club', models.CharField(default='Cerro Navia', max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='athlete_team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Franco', max_length=40, verbose_name='Nombre')),
                ('last_name', models.CharField(default='Vega', max_length=40, verbose_name='Apellido')),
                ('age', models.CharField(default='24', max_length=40)),
                ('email', models.CharField(default='hola@hola.com', max_length=40)),
                ('status', models.CharField(default='noActive', max_length=40)),
                ('team', models.CharField(default='noTeam', max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='other_person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Franco', max_length=40, verbose_name='Nombre')),
                ('last_name', models.CharField(default='Vega', max_length=40, verbose_name='Apellido')),
                ('age', models.CharField(default='24', max_length=40)),
                ('email', models.CharField(default='hola@hola.com', max_length=40)),
                ('status', models.CharField(default='noActive', max_length=40)),
                ('event', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='team_name', max_length=40)),
                ('total_atheteles', models.CharField(default='total_ins', max_length=40)),
                ('event', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Team_championship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(default='event_title', max_length=40, verbose_name='Titulo del evento')),
                ('event_type', models.CharField(default='event_type', max_length=40, verbose_name='Tipo de evento')),
                ('event_place', models.CharField(default='event_place', max_length=30, verbose_name='Lugar del evento')),
                ('event_date', models.DateField(default='2020-11-09')),
                ('init_hour', models.TimeField(default='08:00 a.m', verbose_name='Hora inicial')),
                ('finish_hour', models.TimeField(default='09:00 a.m', verbose_name='Hora Final')),
                ('status', models.CharField(default='Por realizar', max_length=40, verbose_name='Estado')),
                ('observation', models.CharField(default='observation', max_length=300, verbose_name='Oberservaciones')),
                ('max_teams', models.CharField(default='10', max_length=40, verbose_name='Cantidad maxima de equipos')),
                ('ins_teams', models.CharField(default='0', max_length=10, verbose_name='Equipos inscritos')),
                ('organizer', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='Login.Client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Single_championship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(default='event_title', max_length=40, verbose_name='Titulo del evento')),
                ('event_type', models.CharField(default='event_type', max_length=40, verbose_name='Tipo de evento')),
                ('event_place', models.CharField(default='event_place', max_length=30, verbose_name='Lugar del evento')),
                ('event_date', models.DateField(default='2020-11-09')),
                ('init_hour', models.TimeField(default='08:00 a.m', verbose_name='Hora inicial')),
                ('finish_hour', models.TimeField(default='09:00 a.m', verbose_name='Hora Final')),
                ('status', models.CharField(default='Por realizar', max_length=40, verbose_name='Estado')),
                ('observation', models.CharField(default='observation', max_length=300, verbose_name='Oberservaciones')),
                ('max_athletes', models.IntegerField(default=1, verbose_name='Cantidad maxima de deportistas')),
                ('ins_athletes', models.CharField(default='0', max_length=10, verbose_name='Deportistas inscritos')),
                ('organizer', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='Login.Client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Other_event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(default='event_title', max_length=40, verbose_name='Titulo del evento')),
                ('event_type', models.CharField(default='event_type', max_length=40, verbose_name='Tipo de evento')),
                ('event_place', models.CharField(default='event_place', max_length=30, verbose_name='Lugar del evento')),
                ('event_date', models.DateField(default='2020-11-09')),
                ('init_hour', models.TimeField(default='08:00 a.m', verbose_name='Hora inicial')),
                ('finish_hour', models.TimeField(default='09:00 a.m', verbose_name='Hora Final')),
                ('status', models.CharField(default='Por realizar', max_length=40, verbose_name='Estado')),
                ('observation', models.CharField(default='observation', max_length=300, verbose_name='Oberservaciones')),
                ('max_person', models.IntegerField(default=1)),
                ('organizer', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='Login.Client')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
