# Generated by Django 3.1.7 on 2021-04-30 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('Eventos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete_team',
            name='team',
        ),
        migrations.RemoveField(
            model_name='other_event',
            name='organizer',
        ),
        migrations.RemoveField(
            model_name='single_championship',
            name='organizer',
        ),
        migrations.RemoveField(
            model_name='team',
            name='total_atheteles',
        ),
        migrations.RemoveField(
            model_name='team_championship',
            name='organizer',
        ),
        migrations.AddField(
            model_name='athlete_team',
            name='my_team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Eventos.team'),
        ),
        migrations.AddField(
            model_name='athlete_team',
            name='position',
            field=models.CharField(default='Titular', max_length=7),
        ),
        migrations.AddField(
            model_name='other_event',
            name='content_type',
            field=models.ForeignKey(default=1, limit_choices_to=models.Q(models.Q(('app_label', 'Login'), ('model', 'client')), models.Q(('app_label', 'Login'), ('model', 'admin')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='other_event',
            name='ins_person',
            field=models.IntegerField(default=0, verbose_name='Participantes inscritos'),
        ),
        migrations.AddField(
            model_name='other_event',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='single_championship',
            name='content_type',
            field=models.ForeignKey(default=1, limit_choices_to=models.Q(models.Q(('app_label', 'Login'), ('model', 'client')), models.Q(('app_label', 'Login'), ('model', 'admin')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='single_championship',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='team',
            name='athletes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='max_atheteles',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='team',
            name='max_reserve',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='team',
            name='reserve',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team_championship',
            name='content_type',
            field=models.ForeignKey(default=1, limit_choices_to=models.Q(models.Q(('app_label', 'Login'), ('model', 'client')), models.Q(('app_label', 'Login'), ('model', 'admin')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='team_championship',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='age',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Eventos.single_championship'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='first_name',
            field=models.CharField(default='Nombre', max_length=40, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='last_name',
            field=models.CharField(default='Apellido', max_length=40, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='status',
            field=models.CharField(default='Inscrito', max_length=40),
        ),
        migrations.AlterField(
            model_name='athlete_team',
            name='age',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='athlete_team',
            name='first_name',
            field=models.CharField(default='Nombre', max_length=40, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='athlete_team',
            name='last_name',
            field=models.CharField(default='Apellido', max_length=40, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='athlete_team',
            name='status',
            field=models.CharField(default='Inscrito', max_length=40),
        ),
        migrations.AlterField(
            model_name='other_event',
            name='event_date',
            field=models.DateField(default='2020-11-09', verbose_name='Fecha del evento'),
        ),
        migrations.AlterField(
            model_name='other_event',
            name='event_place',
            field=models.IntegerField(choices=[(1, 'Multicancha'), (2, 'Pista Atlética'), (3, 'Psicina'), (4, 'Cancha Sintetica'), (5, 'Gimnasio completo'), (6, 'Lugar externo')], default=6, verbose_name='Lugar del evento'),
        ),
        migrations.AlterField(
            model_name='other_event',
            name='event_type',
            field=models.IntegerField(choices=[(1, 'Evento en general'), (2, 'Torneo deportivo individual'), (3, 'Torneo deportivo por equipos'), (4, 'Otro tipo de evento')], default=3, verbose_name='Tipo de evento'),
        ),
        migrations.AlterField(
            model_name='other_event',
            name='finish_hour',
            field=models.TimeField(default='09:01:00', verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='other_event',
            name='init_hour',
            field=models.TimeField(default='08:01:00', verbose_name='Hora inicial'),
        ),
        migrations.AlterField(
            model_name='other_event',
            name='max_person',
            field=models.IntegerField(default=50, verbose_name='Cantidad maxima de participantes'),
        ),
        migrations.AlterField(
            model_name='other_event',
            name='status',
            field=models.IntegerField(choices=[(1, 'Por realizar'), (2, 'Iniciado'), (3, 'Finalizado'), (4, 'Suspendido')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='other_person',
            name='age',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='other_person',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Eventos.other_event'),
        ),
        migrations.AlterField(
            model_name='other_person',
            name='first_name',
            field=models.CharField(default='Nombre', max_length=40, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='other_person',
            name='last_name',
            field=models.CharField(default='Apellido', max_length=40, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='other_person',
            name='status',
            field=models.CharField(default='Inscrito', max_length=40),
        ),
        migrations.AlterField(
            model_name='single_championship',
            name='event_date',
            field=models.DateField(default='2020-11-09', verbose_name='Fecha del evento'),
        ),
        migrations.AlterField(
            model_name='single_championship',
            name='event_place',
            field=models.IntegerField(choices=[(1, 'Multicancha'), (2, 'Pista Atlética'), (3, 'Psicina'), (4, 'Cancha Sintetica'), (5, 'Gimnasio completo'), (6, 'Lugar externo')], default=6, verbose_name='Lugar del evento'),
        ),
        migrations.AlterField(
            model_name='single_championship',
            name='event_type',
            field=models.IntegerField(choices=[(1, 'Evento en general'), (2, 'Torneo deportivo individual'), (3, 'Torneo deportivo por equipos'), (4, 'Otro tipo de evento')], default=3, verbose_name='Tipo de evento'),
        ),
        migrations.AlterField(
            model_name='single_championship',
            name='finish_hour',
            field=models.TimeField(default='09:01:00', verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='single_championship',
            name='init_hour',
            field=models.TimeField(default='08:01:00', verbose_name='Hora inicial'),
        ),
        migrations.AlterField(
            model_name='single_championship',
            name='ins_athletes',
            field=models.IntegerField(default=0, verbose_name='Deportistas inscritos'),
        ),
        migrations.AlterField(
            model_name='single_championship',
            name='max_athletes',
            field=models.IntegerField(default=50, verbose_name='Cantidad maxima de deportistas'),
        ),
        migrations.AlterField(
            model_name='single_championship',
            name='status',
            field=models.IntegerField(choices=[(1, 'Por realizar'), (2, 'Iniciado'), (3, 'Finalizado'), (4, 'Suspendido')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='team',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Eventos.team_championship'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(default='Equipo_Random', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='team_championship',
            name='event_date',
            field=models.DateField(default='2020-11-09', verbose_name='Fecha del evento'),
        ),
        migrations.AlterField(
            model_name='team_championship',
            name='event_place',
            field=models.IntegerField(choices=[(1, 'Multicancha'), (2, 'Pista Atlética'), (3, 'Psicina'), (4, 'Cancha Sintetica'), (5, 'Gimnasio completo'), (6, 'Lugar externo')], default=6, verbose_name='Lugar del evento'),
        ),
        migrations.AlterField(
            model_name='team_championship',
            name='event_type',
            field=models.IntegerField(choices=[(1, 'Evento en general'), (2, 'Torneo deportivo individual'), (3, 'Torneo deportivo por equipos'), (4, 'Otro tipo de evento')], default=3, verbose_name='Tipo de evento'),
        ),
        migrations.AlterField(
            model_name='team_championship',
            name='finish_hour',
            field=models.TimeField(default='09:01:00', verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='team_championship',
            name='init_hour',
            field=models.TimeField(default='08:01:00', verbose_name='Hora inicial'),
        ),
        migrations.AlterField(
            model_name='team_championship',
            name='ins_teams',
            field=models.IntegerField(default=0, verbose_name='Equipos inscritos'),
        ),
        migrations.AlterField(
            model_name='team_championship',
            name='max_teams',
            field=models.IntegerField(default=10, verbose_name='Cantidad maxima de equipos'),
        ),
        migrations.AlterField(
            model_name='team_championship',
            name='status',
            field=models.IntegerField(choices=[(1, 'Por realizar'), (2, 'Iniciado'), (3, 'Finalizado'), (4, 'Suspendido')], default=1, verbose_name='Estado'),
        ),
    ]
