# Generated by Django 3.0.4 on 2020-11-18 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Single_championship',
            fields=[
                ('ievent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Eventos.iEvent')),
                ('max_athletes', models.IntegerField(default=1)),
            ],
            bases=('Eventos.ievent',),
        ),
    ]
