# Generated by Django 3.0.4 on 2020-11-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0002_auto_20201128_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(default='team_name', max_length=40, unique=True),
        ),
    ]
