# Generated by Django 3.0.4 on 2020-11-18 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0003_other_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='iPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='event_title', max_length=40)),
                ('last_name', models.CharField(default='event_title', max_length=40)),
                ('age', models.CharField(default='event_title', max_length=40)),
                ('email', models.CharField(default='event_title', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='event_title', max_length=40)),
                ('total_atheteles', models.CharField(default='event_title', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='athlete',
            fields=[
                ('iperson_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Eventos.iPerson')),
            ],
            bases=('Eventos.iperson',),
        ),
        migrations.CreateModel(
            name='athlete_team',
            fields=[
                ('iperson_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Eventos.iPerson')),
            ],
            bases=('Eventos.iperson',),
        ),
    ]
