# Generated by Django 3.0.4 on 2020-11-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0003_auto_20201128_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='athletes',
            field=models.IntegerField(default=0),
        ),
    ]
