# Generated by Django 3.0.4 on 2020-11-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0004_team_athletes'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete_team',
            name='position',
            field=models.CharField(default='Reserva', max_length=7),
        ),
    ]
