# Generated by Django 3.0.4 on 2020-11-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0005_auto_20201118_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='ievent',
            name='status',
            field=models.CharField(default='Por realizar', max_length=40),
        ),
        migrations.AlterField(
            model_name='team_championship',
            name='max_teams',
            field=models.CharField(default='10', max_length=40),
        ),
    ]
