# Generated by Django 3.0.4 on 2020-11-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0006_team_total_reserve'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='reserve',
            field=models.IntegerField(default=0),
        ),
    ]
