# Generated by Django 3.0.4 on 2020-11-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0006_auto_20201119_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='results',
            field=models.CharField(default='noWin', max_length=40),
        ),
        migrations.AddField(
            model_name='athlete',
            name='status',
            field=models.CharField(default='noTeam', max_length=40),
        ),
        migrations.AddField(
            model_name='athlete',
            name='team',
            field=models.CharField(default='noTeam', max_length=40),
        ),
        migrations.AddField(
            model_name='iperson',
            name='event',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='iperson',
            name='age',
            field=models.CharField(default='24', max_length=40),
        ),
        migrations.AlterField(
            model_name='iperson',
            name='email',
            field=models.CharField(default='hola@hola.com', max_length=40),
        ),
        migrations.AlterField(
            model_name='iperson',
            name='first_name',
            field=models.CharField(default='Franco', max_length=40),
        ),
        migrations.AlterField(
            model_name='iperson',
            name='last_name',
            field=models.CharField(default='Vega', max_length=40),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(default='team_name', max_length=40),
        ),
        migrations.AlterField(
            model_name='team',
            name='total_atheteles',
            field=models.CharField(default='total_ins', max_length=40),
        ),
    ]
