# Generated by Django 3.0.4 on 2020-11-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0007_auto_20201119_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iperson',
            name='event',
        ),
        migrations.AddField(
            model_name='team',
            name='event',
            field=models.IntegerField(default=0),
        ),
    ]
