# Generated by Django 3.0.4 on 2020-11-29 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0007_team_reserve'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='total_atheteles',
            new_name='max_atheteles',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='total_reserve',
            new_name='max_reserve',
        ),
    ]
