# Generated by Django 3.0.4 on 2020-11-19 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0008_auto_20201119_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='athlete_team',
            fields=[
                ('iperson_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Eventos.iPerson')),
                ('team', models.CharField(default='noTeam', max_length=40)),
            ],
            bases=('Eventos.iperson',),
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='team',
        ),
    ]
