# Generated by Django 3.0.4 on 2021-01-16 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
        ('Eventos', '0009_auto_20201130_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete_team',
            name='my_team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Eventos.Team'),
        ),
        migrations.AlterField(
            model_name='other_event',
            name='organizer',
            field=models.ForeignKey(default='4', on_delete=django.db.models.deletion.CASCADE, to='Login.Client'),
        ),
        migrations.AlterField(
            model_name='single_championship',
            name='organizer',
            field=models.ForeignKey(default='4', on_delete=django.db.models.deletion.CASCADE, to='Login.Client'),
        ),
        migrations.AlterField(
            model_name='team_championship',
            name='organizer',
            field=models.ForeignKey(default='4', on_delete=django.db.models.deletion.CASCADE, to='Login.Client'),
        ),
    ]
