# Generated by Django 3.0.4 on 2020-11-19 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0010_auto_20201119_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='club',
            field=models.CharField(default='Cerro Navia', max_length=40),
        ),
    ]
