# Generated by Django 3.0.4 on 2020-11-20 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0008_delete_normal_person'),
        ('Eventos', '0012_other_person_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='ievent',
            name='organizer',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Login.Client'),
        ),
    ]
