# Generated by Django 3.0.4 on 2021-03-20 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0015_auto_20210320_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='other_event',
            name='organizer',
        ),
        migrations.RemoveField(
            model_name='single_championship',
            name='organizer',
        ),
        migrations.RemoveField(
            model_name='team_championship',
            name='organizer',
        ),
        migrations.AlterField(
            model_name='athlete_team',
            name='my_team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Eventos.Team'),
        ),
    ]
