# Generated by Django 3.0.4 on 2021-03-20 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0017_auto_20210320_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete_team',
            name='my_team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Eventos.Team'),
        ),
        migrations.AlterField(
            model_name='other_event',
            name='event_place',
            field=models.IntegerField(choices=[(1, 'Multicancha'), (2, 'Pista Atlética'), (3, 'Psicina'), (4, 'Cancha Sintetica'), (5, 'Gimnasio completo'), (6, 'Lugar Externo')], default=6, verbose_name='Lugar del evento'),
        ),
        migrations.AlterField(
            model_name='other_event',
            name='status',
            field=models.IntegerField(choices=[(1, 'Por realizar'), (2, 'Iniciado'), (3, 'Finalizado'), (4, 'Suspendido')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='single_championship',
            name='event_place',
            field=models.IntegerField(choices=[(1, 'Multicancha'), (2, 'Pista Atlética'), (3, 'Psicina'), (4, 'Cancha Sintetica'), (5, 'Gimnasio completo'), (6, 'Lugar Externo')], default=6, verbose_name='Lugar del evento'),
        ),
        migrations.AlterField(
            model_name='single_championship',
            name='status',
            field=models.IntegerField(choices=[(1, 'Por realizar'), (2, 'Iniciado'), (3, 'Finalizado'), (4, 'Suspendido')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='team_championship',
            name='event_place',
            field=models.IntegerField(choices=[(1, 'Multicancha'), (2, 'Pista Atlética'), (3, 'Psicina'), (4, 'Cancha Sintetica'), (5, 'Gimnasio completo'), (6, 'Lugar Externo')], default=6, verbose_name='Lugar del evento'),
        ),
        migrations.AlterField(
            model_name='team_championship',
            name='status',
            field=models.IntegerField(choices=[(1, 'Por realizar'), (2, 'Iniciado'), (3, 'Finalizado'), (4, 'Suspendido')], default=1, verbose_name='Estado'),
        ),
    ]
