# Generated by Django 3.0.4 on 2021-03-20 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0018_auto_20210320_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete_team',
            name='my_team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Eventos.Team'),
        ),
        migrations.AlterField(
            model_name='other_event',
            name='event_place',
            field=models.IntegerField(choices=[(1, 'Multicancha'), (2, 'Pista Atlética'), (3, 'Psicina'), (4, 'Cancha Sintetica'), (5, 'Gimnasio completo'), (6, 'Lugar externo')], default=6, verbose_name='Lugar del evento'),
        ),
        migrations.AlterField(
            model_name='other_event',
            name='event_type',
            field=models.IntegerField(choices=[(1, 'Evento en general'), (2, 'Torneo deportivo individual'), (3, 'Torneo deportivo por equipos'), (4, 'Otro tipo de evento')], default=3, verbose_name='Tipo de evento'),
        ),
        migrations.AlterField(
            model_name='other_event',
            name='finish_hour',
            field=models.TimeField(default='09:00:00', verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='other_event',
            name='init_hour',
            field=models.TimeField(default='08:00:00', verbose_name='Hora inicial'),
        ),
        migrations.AlterField(
            model_name='single_championship',
            name='event_place',
            field=models.IntegerField(choices=[(1, 'Multicancha'), (2, 'Pista Atlética'), (3, 'Psicina'), (4, 'Cancha Sintetica'), (5, 'Gimnasio completo'), (6, 'Lugar externo')], default=6, verbose_name='Lugar del evento'),
        ),
        migrations.AlterField(
            model_name='single_championship',
            name='event_type',
            field=models.IntegerField(choices=[(1, 'Evento en general'), (2, 'Torneo deportivo individual'), (3, 'Torneo deportivo por equipos'), (4, 'Otro tipo de evento')], default=3, verbose_name='Tipo de evento'),
        ),
        migrations.AlterField(
            model_name='single_championship',
            name='finish_hour',
            field=models.TimeField(default='09:00:00', verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='single_championship',
            name='init_hour',
            field=models.TimeField(default='08:00:00', verbose_name='Hora inicial'),
        ),
        migrations.AlterField(
            model_name='team_championship',
            name='event_place',
            field=models.IntegerField(choices=[(1, 'Multicancha'), (2, 'Pista Atlética'), (3, 'Psicina'), (4, 'Cancha Sintetica'), (5, 'Gimnasio completo'), (6, 'Lugar externo')], default=6, verbose_name='Lugar del evento'),
        ),
        migrations.AlterField(
            model_name='team_championship',
            name='event_type',
            field=models.IntegerField(choices=[(1, 'Evento en general'), (2, 'Torneo deportivo individual'), (3, 'Torneo deportivo por equipos'), (4, 'Otro tipo de evento')], default=3, verbose_name='Tipo de evento'),
        ),
        migrations.AlterField(
            model_name='team_championship',
            name='finish_hour',
            field=models.TimeField(default='09:00:00', verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='team_championship',
            name='init_hour',
            field=models.TimeField(default='08:00:00', verbose_name='Hora inicial'),
        ),
    ]
