# Generated by Django 3.0.4 on 2021-03-20 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0019_auto_20210320_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete_team',
            name='my_team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Eventos.Team'),
        ),
        migrations.AlterField(
            model_name='other_event',
            name='finish_hour',
            field=models.TimeField(default='09:01:00', verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='other_event',
            name='init_hour',
            field=models.TimeField(default='08:01:00', verbose_name='Hora inicial'),
        ),
        migrations.AlterField(
            model_name='single_championship',
            name='finish_hour',
            field=models.TimeField(default='09:01:00', verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='single_championship',
            name='init_hour',
            field=models.TimeField(default='08:01:00', verbose_name='Hora inicial'),
        ),
        migrations.AlterField(
            model_name='team_championship',
            name='finish_hour',
            field=models.TimeField(default='09:01:00', verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='team_championship',
            name='init_hour',
            field=models.TimeField(default='08:01:00', verbose_name='Hora inicial'),
        ),
    ]
