# Generated by Django 3.0.4 on 2021-03-20 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0020_auto_20210320_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete_team',
            name='my_team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Eventos.Team'),
        ),
        migrations.AlterField(
            model_name='other_event',
            name='object_id',
            field=models.PositiveIntegerField(choices=[(1, 'Por realizar'), (2, 'Iniciado'), (3, 'Finalizado'), (4, 'Suspendido')]),
        ),
        migrations.AlterField(
            model_name='single_championship',
            name='object_id',
            field=models.PositiveIntegerField(choices=[(1, 'Por realizar'), (2, 'Iniciado'), (3, 'Finalizado'), (4, 'Suspendido')]),
        ),
        migrations.AlterField(
            model_name='team_championship',
            name='object_id',
            field=models.PositiveIntegerField(choices=[(1, 'Por realizar'), (2, 'Iniciado'), (3, 'Finalizado'), (4, 'Suspendido')]),
        ),
    ]
