# Generated by Django 3.1.7 on 2021-04-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0021_auto_20210320_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other_event',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='single_championship',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='team_championship',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
