# Generated by Django 3.0.4 on 2020-11-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='corp',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
