# Generated by Django 3.0.4 on 2020-11-18 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('text', models.CharField(blank=True, default=None, max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
