# Generated by Django 3.0.4 on 2020-11-18 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0005_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
