# Generated by Django 3.0.4 on 2020-11-18 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0007_normal_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Normal_person',
        ),
    ]
